CREATE SCHEMA api;

CREATE TABLE api.users (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	username TEXT NOT NULL,
	password TEXT NOT NULL,
	reverse_string BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO api.users (username, password) VALUES
	('shaco', '123'), ('clone', '456');

CREATE ROLE web_anon NOLOGIN;
GRANT USAGE ON SCHEMA api TO web_anon;
GRANT SELECT, UPDATE(reverse_string) ON api.users TO web_anon;
GRANT web_anon TO authenticator;
